### ISSUE TITLE
using depricated NumberEntity

### ISSUE THREAD

**Issue by ChristophCaina** [ChristophCaina/openwbmqtt#22]
Logger: homeassistant.components.number
Source: components/number/__init__.py:462
Integration: Nummer ([documentation](https://www.home-assistant.io/integrations/number), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+number%22))
First occurred: 14. Juli 2022 um 16:10:04 (5 occurrences)
Last logged: 14. Juli 2022 um 16:10:04

    Entity number.openWB-Mindestladestrom (Modus Min+PV-Laden) (<class 'custom_components.openwbmqtt.number.openWBNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
    Entity number.openWB-CP1-Ladestromvorgabe (Modus Sofortladen) (<class 'custom_components.openwbmqtt.number.openWBNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
    Entity number.openWB-CP1-Energiebegrenzung (Modus Sofortladen) (<class 'custom_components.openwbmqtt.number.openWBNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
    Entity number.openWB-CP1-SoC-Begrenzung (Modus Sofortladen) (<class 'custom_components.openwbmqtt.number.openWBNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.
    Entity number.openWB-CP1-Aktueller SoC (Manuelles SoC Modul) (<class 'custom_components.openwbmqtt.number.openWBNumber'>) is using deprecated NumberEntity features which will be unsupported from Home Assistant Core 2022.10, please report it to the custom component author.

**Comment by ChristophCaina** [comment]
the following attributes needs to be renamed:

unit_of_measurement -> native_unit_of_measurement
min_value -> native_min_value
max_value -> native_max_value
step -> native_step
value -> native_value

discussion on homeassistant.io forum:
https://community.home-assistant.io/t/depricated-numberentity-features/440282

**Comment by ChristophCaina** [comment]
https://developers.home-assistant.io/blog/2022/06/14/number_entity_refactoring/

**Comment by riesi77** [comment]
Hi Christoph,
stumbled over this fork after seeing your statement on https://community.home-assistant.io/t/depricated-numberentity-features/440282/2
Are you still planning on fixing that and releasing your fork of the integration?

**Comment by ChristophCaina** [comment]
Hi,
honestly speaking - I don't know.
I am still facing several other issues with the integration for which I don't have any Idea how to fix them...

One major issue I have is in fact, that every then and now, the integration receives old values from MQTT.
- They are then adding up on the measurement sensors (charge today, charge total, etc.)...

I found a workaround in NodeRed - by sending a periodic command "refresh mqtt=1"... but it is still not working 100%...

I think, that I will try to fix some of the issues - but at the moment, I have still some other projects on my todo list - which I need to focus on...
If you want to try it on your own and contribute, please feel free to do so :)
