### ISSUE TITLE
mqtt payload from homeassistant mqtt-broker provides old data after disconnect (reboot for example)

### ISSUE THREAD

**Issue by ChristophCaina** [ChristophCaina/openwbmqtt#25]
MQTT does sometimes send old values to the Integration (#1 #2 #17 #18) - based on information from the openWB forum, this could be solved by sending **openWB/set/RenewMQTT** = **1** to the wallbox.

Currently, this is implemented in NodeRed - but not yet in the integration.

**Comment by onkelbeh** [comment]
This won't help (#1), these are the values that are re-sent after RenewMQTT:

```
2022-09-25 08:36:43 Topic: openWB/set/pv/1/faultState Message: 0
2022-09-25 08:36:43 Topic: openWB/set/pv/1/faultStr Message: "Kein Fehler."
2022-09-25 08:36:38 Topic: openWB/set/evu/VPhase3 Message: 228
2022-09-25 08:36:38 Topic: openWB/set/evu/VPhase2 Message: 230
2022-09-25 08:36:38 Topic: openWB/set/evu/VPhase1 Message: 233
2022-09-25 08:36:38 Topic: openWB/set/evu/W Message: 2316
2022-09-25 08:36:38 Topic: openWB/set/evu/APhase3 Message: 0.65
2022-09-25 08:36:38 Topic: openWB/set/evu/APhase2 Message: 9.09
2022-09-25 08:36:38 Topic: openWB/set/evu/APhase1 Message: 0.33
2022-09-25 08:36:34 Topic: openWB/set/evu/faultStr Message: Kein Fehler
2022-09-25 08:36:34 Topic: openWB/set/evu/faultState Message: 0
2022-09-25 08:36:33 Topic: openWB/set/evu/VPhase3 Message: 228
2022-09-25 08:36:33 Topic: openWB/set/evu/VPhase2 Message: 230
2022-09-25 08:36:33 Topic: openWB/set/evu/VPhase1 Message: 233
2022-09-25 08:36:33 Topic: openWB/set/evu/W Message: 2316
2022-09-25 08:36:33 Topic: openWB/set/evu/APhase3 Message: 0.65
2022-09-25 08:36:33 Topic: openWB/set/evu/APhase2 Message: 9.09
2022-09-25 08:36:33 Topic: openWB/set/evu/APhase1 Message: 0.33
2022-09-25 08:36:33 Topic: openWB/set/pv/1/faultState Message: 0
2022-09-25 08:36:33 Topic: openWB/set/pv/1/faultStr Message: "Kein Fehler."
2022-09-25 08:36:28 Topic: openWB/set/evu/VPhase3 Message: 228
2022-09-25 08:36:28 Topic: openWB/set/evu/VPhase2 Message: 230
2022-09-25 08:36:28 Topic: openWB/set/evu/VPhase1 Message: 233
2022-09-25 08:36:28 Topic: openWB/set/evu/W Message: 2316
2022-09-25 08:36:28 Topic: openWB/set/evu/APhase3 Message: 0.65
2022-09-25 08:36:28 Topic: openWB/set/evu/APhase2 Message: 9.09
2022-09-25 08:36:28 Topic: openWB/set/evu/APhase1 Message: 0.33
2022-09-25 08:36:24 Topic: openWB/set/evu/faultStr Message: Kein Fehler
2022-09-25 08:36:24 Topic: openWB/set/evu/faultState Message: 0
2022-09-25 08:36:23 Topic: openWB/set/evu/VPhase3 Message: 228
2022-09-25 08:36:23 Topic: openWB/set/evu/VPhase2 Message: 230
2022-09-25 08:36:23 Topic: openWB/set/evu/VPhase1 Message: 233
2022-09-25 08:36:23 Topic: openWB/set/evu/W Message: 2323
2022-09-25 08:36:23 Topic: openWB/set/evu/APhase3 Message: 0.65
2022-09-25 08:36:23 Topic: openWB/set/evu/APhase2 Message: 9.12
2022-09-25 08:36:23 Topic: openWB/set/evu/APhase1 Message: 0.33
2022-09-25 08:36:23 Topic: openWB/set/pv/1/faultState Message: 0
2022-09-25 08:36:23 Topic: openWB/set/pv/1/faultStr Message: "Kein Fehler."
01
```

**Comment by ChristophCaina** [comment]
are you sure?
first, these are "set" commands - which mean, it would set topic - instead of get.

Also, I am receiving these topics in my nodered flow all the time - even without sending the renewMQTT (after removing it)
But: When I had wrong charging stats, these were updated after sending the renewMQTT.

Even if it would not help - it would be interesting, why I have this issue - but others not (If I remember, you told me you haven't seen this behave so far) ?

**Comment by onkelbeh** [comment]
Not really sure, I have sent `1` to `openWB/openWB/set/RenewMQTT`, and the post above is the output of the wallbox's MQTT debug log of the next few seconds. The debug log is flushed as soon as you send the `1`.

I use MQTT Explorer, if "show activity" is enabled, the newly sent values are highlighted for a second, and the highlights (from the bridged mosquitto) match the debug log. On the other hand, the timestamp of some other values is updated, the `last-updated` stamp in Home Assistant stays untouched:

<img width="774" alt="grafik" src="https://user-images.githubusercontent.com/42828703/192153493-2bb6e53c-eaa1-45c1-b2cb-e99b268e03fd.png">


I am still searching for the optimal place to sent the `1` during the modules init, at least this will not hurt, though I have not (yet) seen any inappropriate value sent from the box. But - I have it running for only a few days, only 2 charges so far.

In your place, I would rather suggest looking for some bad persistance / retains set an (if possible), check if `retain` is set on some of the values, or start with a clean MQTT config. But I am not sure what exactly (of theses settings) is replicated over the bridge.

**Comment by ChristophCaina** [comment]
@onkelbeh : Just had the same issue again with the "Geladene Energie Gesamt"...

"Geladene kWh (Jahr)" is a utility meter which does sum up the energy for the whole year...
![grafik](https://user-images.githubusercontent.com/26391061/192634726-167ade34-92a1-4ccb-962d-a40532462c6b.png)

![grafik](https://user-images.githubusercontent.com/26391061/192634735-70f396d3-ac37-4f75-bcf3-609b7675dc10.png)

after a short period of time, it switched back to the correct state - I guess, because the renew mqtt was sent:
![grafik](https://user-images.githubusercontent.com/26391061/192634917-7feb2363-82d8-469d-b917-74a75770ae26.png)

**Comment by onkelbeh** [comment]
What exactly are you doing in the moment the value drops? 

Perhaps you could try a 
```bash
# mosquitto_sub -v -t "openWB/lp/1/kWhCounter" -h {ip_of_wallbox}
```
or
```
# mosquitto_sub -v -t "openWB/openWB/lp/1/kWhCounter" -h {ip_of_homeassistants_mqtt}
```
to track down the source of all evil :-)
As I told you already in an earlier mail, I have not seen anything like that, after a couple of reboots, and 4 charges in my list.

**Comment by ChristophCaina** [comment]
honestly speaking:
I haven't done much in that case.
To be more specific: I just restarted HomeAssistant (at least, when the last "drop" happened)

I just did another reboot (due to an update) and monitored both - the OpenWB as well as the HomeAssistant MQTT...
It seems that the issue is within the MQTT Broker from HomeAssistant:

![grafik](https://user-images.githubusercontent.com/26391061/192899246-13863c97-2327-434f-b3d1-c2b61f72e3b5.png)

![grafik](https://user-images.githubusercontent.com/26391061/192899391-3584884c-292e-496b-8cfa-251418e34480.png)
![grafik](https://user-images.githubusercontent.com/26391061/192899474-a3cbdd87-d198-4c72-8c0b-e4daa9847246.png)

**Comment by ChristophCaina** [comment]
OK, it seems that this always happens, when the MQTT Broker from HomeAssistant will be disconnected
![grafik](https://user-images.githubusercontent.com/26391061/193227411-5ea4daba-d48c-4227-8650-a7dced855bc8.png)

**Comment by ChristophCaina** [comment]
these topics might be interesting in this case:

- https://community.home-assistant.io/t/persistent-mqtt-after-reboot/12642/3

"According to this: [https://mosquitto.org/man/mosquitto-conf-5.html 177](https://mosquitto.org/man/mosquitto-conf-5.html) the default mosquitto setting is to save latest messages every 30 minutes so a local DB file.
The above will tell it to save every 30 seconds…

After that every mqtt sensor that is looking on a particular queue, get’s the latest message as soon as HA restarts (either from a normal restart / reboot / power outage)"

- https://community.home-assistant.io/t/mqtt-value-after-restart-ha/66960/3

It might be caused by a misconfiguration of the mosquitto - working as a bridge in HomeAssistant.
The current Configuration of the "mosquitto.conf" file in HomeAssistant is:

```
#
# bridge to openWB Wallbox
#
connection openwb
address xxx.xxx.xxx.xxx:1883
start_type automatic
topic openWB/# both 2
local_clientid openwb.mosquitto
try_private  false
cleansession true
```

**Comment by onkelbeh** [comment]
did the restart your of homeassistant mentioned in the last post also restart mosquitto?
perhaps the mosquitto at the ha machine loads some old shit at startup (because it is not shut cleanly).

**Comment by ChristophCaina** [comment]
hm... that could be.
the Mosquitto in HA is running as an Addon... therefore, it is (afaik) a docker container running seperately and independend from the HA Core.
When restarting HomeAssistant due to an core- or integration addon, it might be, that the Addon does not restart.

How did you install the addon / integration?
Are you using the HA Mosquitto Broker, too?

Basically, I followed the instructions on this blog post:
http://tech-engineering.de/home-assistant-und-openwb/

btw:
I just saw in the openWB forum that someone else has the same issues...
So, providing some more information on how this can be fixed would be interesting for others as well :)

[can be shared in wiki / discussions]

**Comment by ChristophCaina** [comment]
https://pagefault.blog/2020/02/05/how-to-set-up-persistent-storage-for-mosquitto-mqtt-broker/

> Bridges and persistence
> 
> Bridge is a normal MQTT connection but instead of ordinary client connecting to a broker, it is a connection between two brokers. Therefore the cleansession flag is also available for bridge connections. When the connecting broker sets the cleansession to false it will cause the remote broker to keep subscriptions and queued message in case the network connection drops. This is usually the desired functionality when using a local broker in an embedded device, so the remote cloud broker will queue and then deliver messages when the device comes back online.
> 
> In Mosquitto, the cleansession can be set for each bridge connection separately.

based on this article, I think the "cleansession" statement should be set to false instead of true.

> **When the connecting broker sets the cleansession to false it will cause the remote broker to keep subscriptions and queued message in case the network connection drops.**

mosquitto.conf for testing:

```
#
# bridge to openWB Wallbox
#
connection openwb
address 192.168.52.71:1883
start_type automatic
topic openWB/# both 2
local_clientid openwb.mosquitto
try_private false
cleansession true
persistence true
autosave_on_changes true
```

**Comment by ChristophCaina** [comment]
the changed mosquitto.conf did not solve the behave.
For testing the case, I did charge the car with ~5.31 kWh
after that, I restarted HomeAssistant Core

![grafik](https://user-images.githubusercontent.com/26391061/195350174-04c4659a-a616-43af-85da-01d70d898e49.png)
![grafik](https://user-images.githubusercontent.com/26391061/195350206-6067af76-7016-444f-9a57-96f8b623ad60.png)

![grafik](https://user-images.githubusercontent.com/26391061/195350229-c98c1984-a55b-437d-84e9-0d8daf952bcd.png)

Trying cleansession = false as mentioned in the quote below

> Bridges and persistence
> 
> Bridge is a normal MQTT connection but instead of ordinary client connecting to a broker, it is a connection between two brokers. Therefore the cleansession flag is also available for bridge connections. When the connecting broker sets the cleansession to false it will cause the remote broker to keep subscriptions and queued message in case the network connection drops. This is usually the desired functionality when using a local broker in an embedded device, so the remote cloud broker will queue and then deliver messages when the device comes back online.
> 
> In Mosquitto, the cleansession can be set for each bridge connection separately.

**Comment by ChristophCaina** [comment]
same behave with Cleansession=false (and the other options disabled, too)

Counters after a short charging session:
![grafik](https://user-images.githubusercontent.com/26391061/195359466-d507d835-a765-45bb-8518-a47c4305a33d.png)

Counters after rebooting HomeAssistant
![grafik](https://user-images.githubusercontent.com/26391061/195358518-3853eb40-3ffe-4555-a249-7e005cb65218.png)

this time, the values did not "recover" automatically.

**Comment by ChristophCaina** [comment]
the next test with
cleansession=false
persistence true
autosave_on_changes true

Counters after charging:
![grafik](https://user-images.githubusercontent.com/26391061/195361499-10a68ce3-0cba-4b63-aaa9-5fb2005edac4.png)

and counters after rebooting HA-Core
![grafik](https://user-images.githubusercontent.com/26391061/195361588-0641e176-6ffe-4c6d-9e58-66adcaa129e7.png)

**Comment by ChristophCaina** [comment]
Counters are restoring after publishing openWB/set/RenewMQTT 1

**Comment by ChristophCaina** [comment]
closed.
Tested an installation without using another MQTT Broker acting as bridge.

**Comment by ChristophCaina** [comment]
Issue reopen - just came back yesterday evening, without a known root cause yet.
This time, no MQTT Broker was acting in between HomeAssistant and the OpenWB - unfortunately, most sensors are showing a reset to a previous state between 23:10:00 and 23:16:00

CP active
![grafik](https://user-images.githubusercontent.com/26391061/196597451-874e2833-3186-45f4-b21c-75a945481aeb.png)

CP1 unlocked
![grafik](https://user-images.githubusercontent.com/26391061/196597506-70afbf5a-26b7-4030-9454-1e9e686a82d4.png)

charged kwh (total)
![grafik](https://user-images.githubusercontent.com/26391061/196597527-15473702-3ed2-4fb7-a865-f74a0cd7f2d2.png)
![grafik](https://user-images.githubusercontent.com/26391061/196597544-32309e43-7f07-4e41-9a82-7d6afc50a574.png)

and also the others.
I am not aware of any reboot of the OpenWB at that time... I am unsure if HA has rebooted due to setup changes... (that could be)
My other (old) HA instance does not show this behave at the same time...
[But IF the OpenWB would have sent older values due to a reboot, even the bridged MQTT Broker would have received these older message and the old HA setup should also show such drops]

This time, I am pretty sure that this is related to the MQTT Broker from the OpenWB... but I can't access the logs right now :-(

**Comment by ChristophCaina** [comment]
issue was no longer observed...
