### ISSUE TITLE
decreasing sensor.openwb_uptime update frequency

### ISSUE THREAD

**Issue by northalpha** [ChristophCaina/openwbmqtt#32]
Hi first of all, aweseome addon/integration!

using the latest update the sensor `sensor.openwb_uptime` is updated minutely, which by itself is no issue at all, but maybe the update frequency is to often. This is spamming/fillup the history/database from HA with useless information.

may i ask to decrease the frequency to maybe daily? 

I am very aware of that i might just deactivate the sensor to get rid f these messages, but just as an idea for not that "experienced" users "just using your integration" :)

**Comment by ChristophCaina** [comment]
Hi,
Thanks for the information.

The main issue here is that the integration is just listen to what it receives from the wallbox over MQTT - and the wallbox is sending the Uptime value in that frequency.

I am not sure, if I will be able to change this within the code... 
There are probably several other sensors which behave in a similar way...

**Comment by ChristophCaina** [comment]
Hi @northalpha,

first of all, the credits should go to @ a529987659852 who has created the addon.
I've just forked it trying to create some fixes and additional sensors :)

I had another thought of your reply regarding the Uptime Sensor... and I think, it could work if we MAYBE remove the minutes from the sensor - in that case, the integration would still receive the MQTT Topic, but the update frequency of the sensor should change to hourly.

On the other hand, monitoring is what it is... and if we want to monitor the uptime of the Wallbox, then it SHOULD include the whole uptime information (in my opinion)
I have several other sensors where I receive uptime information every minute... and yes, I can see that this is causing a lot of data in the HA Database...

as an Workaround, I would suggest to exclude the openwb uptime sensor from the HomeAssistant Recorder:

```
recorder:
  exclude:
    entity_globs:
      - sensor.*uptime*
```
or:

```
recorder:
  exclude:
    entities:
      - sensor.openwb_uptime
 ```
 
![grafik](https://user-images.githubusercontent.com/26391061/195195491-ae1eec9b-799d-4c73-b1cc-e7606ca29b03.png)

**Comment by ChristophCaina** [comment]
another option could be to calculate the timestamp...

I've checked other "uptime" entities in my HomeAssistant instance, and for example, the fritzbox is just providing a Timestamp when it connected:

FRITZ!Box 7590 Connection Uptime:
![grafik](https://user-images.githubusercontent.com/26391061/195181874-a1d2f958-03e3-4baf-a25d-c36ef78c7f65.png)

This will then be stored until the time stamp will change.
In HomeAssistant, you can further more select different options how to display that information:

![grafik](https://user-images.githubusercontent.com/26391061/195182898-2a1b5022-c460-4fdb-bb71-a17dd98a4c6d.png)

But at the moment, I don't have an idea how to calculate the time stamp or if this might be provided by the OpenWB (I've seen something, that could be related to that, but I need to check it further)
